### ISSUE TITLE
Does this support using any android sdk

### ISSUE THREAD

**Issue by ghost** [MiqueiasDevGames/export-godot-to-android-without-gradle-32bits-and-64bits#1]
I want to use multiple android Feature like in app rating, ads, . So it is important to use sdk. Does it support installing sdk

**Comment by MiqueiasDevGames** [comment]
Yea!



But if you need more dependencies just add in
AddAdmobPlugin.sh, it's very simple, put the plugin in the godot plugin folder as you normally would, then run the
AddAdmobPlugin.sh , it even asks to do so.

The important thing is to always add extra dependencies in the folder: Admob_Android_Dependency


The Android_Dependency folder goes to the main android classes.dex and it has a size limit so don't add anything else there after running DownloadDependency.sh

just know the dependencies that the resource you want to use needs and add it to the folder

Admob_Android_Dependency

I get the download links from https://mvnrepository.com/


For example now I'm putting firebase notifications, there all adding all the necessary dependencies, it's trial and error, using a lot of logcat, to see what's missing

In addition, I'm still improving the project to make things easier to add new android features.



But for now Admob already works, using the plugin I mentioned.

Anyway
When the project is finished, you will have:

Admob
and
firebase notifications
and
Android share

I'll try to put everything that is important for a game to be successful, I'll try to put the app rating too

If you need anything else, you need to look for dependencies and see what changes are needed in AndroidManifest.xml

**Comment by MiqueiasDevGames** [comment]
I've even launched a game using this project: https://play.google.com/store/apps/details?id=com.matematica.canhaokids

Has Admob and Android Share Button


For the Share Button I used the plugin https://github.com/Shin-NiL/Godot-Share

as this plugin does not need extra dependencies just add the .aar lib in the godot plugins folder as well as the Admob plugin, before running AddAdmobPlugin.sh

**Comment by ghost** [comment]
> I've even launched a game using this project: https://play.google.com/store/apps/details?id=com.matematica.canhaokids
> 
> Has Admob and Android Share Button
> 
> 
> For the Share Button I used the plugin https://github.com/Shin-NiL/Godot-Share
> 
> as this plugin does not need extra dependencies just add the .aar lib in the godot plugins folder as well as the Admob plugin, before running AddAdmobPlugin.sh

Is there any functionality for in app rating

**Comment by MiqueiasDevGames** [comment]
No!

Why would you want to use my project to export your game, are you on a 32-bit system?

**Comment by MiqueiasDevGames** [comment]
@hani09876 
I was researching here in a few days I will upload a new version with the rating app too, very easy to put

**Comment by hani09876** [comment]
> No!
> 
> Why would you want to use my project to export your game, are you on a 32-bit system?

I am on 64 bit

**Comment by hani09876** [comment]
> @hani09876 
> I was researching here in a few days I will upload a new version with the rating app too, very easy to put

I don't want to use admob. Cause admob place add limits without any reason.

**Comment by hani09876** [comment]
> > @hani09876 
> > I was researching here in a few days I will upload a new version with the rating app too, very easy to put
> 
> I don't want to use admob. Cause admob place add limits without any reason.

Will you add applovin in this system

**Comment by MiqueiasDevGames** [comment]
But are you having trouble using the godot plugins?


https://github.com/DrMoriarty/godot-applovin-max
https://github.com/DrMoriarty/godot-applovin


Okay, now you have Admob, Firebase Notifications, Android Share and App Review Rating

**Comment by ghost** [comment]
> But are you having trouble using the godot plugins?
> 
> 
> https://github.com/DrMoriarty/godot-applovin-max
> https://github.com/DrMoriarty/godot-applovin
> 
> 
> Okay, now you have Admob, Firebase Notifications, Android Share and App Review Rating
> 
> 
> 

Yes. Because each plugin have a different system for using. Some needs to add module, some don't. Some needs to add as a  node, some don't.

But thanks you for your nice help and support.

**Comment by ghost** [comment]
You are a great developer. Will you make some video on creating android plugin for godot. And upload them on YouTube. In this way you will get some extra money and we will get some help. 

If you do so i will subscribe your channel for all of my friends mobile.

**Comment by MiqueiasDevGames** [comment]
@hani09876 

Well, actually I didn't do anything much, I'm just on a 32bit pc and with google play it only accepts aab formats to send app and the android build tools don't support 32bit systems anymore, I had to find a way to generate aab, so I use the godot plugins made by other people, by the links I left you can see.

Of course I check with reverse engineering to see if there is no hack and that's it.


As for the godot plugin made by DrMoriarty for AppLovin which one do you want to use, do you want to use AppLovin as a mediation or just AppLovin?

**Comment by ghost** [comment]
> @hani09876 
> 
> Well, actually I didn't do anything much, I'm just on a 32bit pc and with google play it only accepts aab formats to send app and the android build tools don't support 32bit systems anymore, I had to find a way to generate aab, so I use the godot plugins made by other people, by the links I left you can see.
> 
> Of course I check with reverse engineering to see if there is no hack and that's it.
> 
> 
> As for the godot plugin made by DrMoriarty for AppLovin which one do you want to use, do you want to use AppLovin as a mediation or just AppLovin?

Can you tell me how can i use this plugin ? I mean what will be the code to call for review? I was trying by this way![157589782-9213ee8e-7c6b-41c1-9ddb-88723a5e8885.png](https://user-images.githubusercontent.com/92350126/157653048-a486a3c3-d8e6-47ea-bcfd-ec19eb57bd37.png)

**Comment by hani09876** [comment]
> > @hani09876 
> > 
> > Well, actually I didn't do anything much, I'm just on a 32bit pc and with google play it only accepts aab formats to send app and the android build tools don't support 32bit systems anymore, I had to find a way to generate aab, so I use the godot plugins made by other people, by the links I left you can see.
> > 
> > Of course I check with reverse engineering to see if there is no hack and that's it.
> > 
> > 
> > As for the godot plugin made by DrMoriarty for AppLovin which one do you want to use, do you want to use AppLovin as a mediation or just AppLovin?
> 
> Can you tell me how can i use this plugin ? I mean what will be the code to call for review? I was trying by this way![157589782-9213ee8e-7c6b-41c1-9ddb-88723a5e8885.png](https://user-images.githubusercontent.com/92350126/157653048-a486a3c3-d8e6-47ea-bcfd-ec19eb57bd37.png)

Are you on discord?

**Comment by ghost** [comment]
> @hani09876 
> 
> Well, actually I didn't do anything much, I'm just on a 32bit pc and with google play it only accepts aab formats to send app and the android build tools don't support 32bit systems anymore, I had to find a way to generate aab, so I use the godot plugins made by other people, by the links I left you can see.
> 
> Of course I check with reverse engineering to see if there is no hack and that's it.
> 
> 
> As for the godot plugin made by DrMoriarty for AppLovin which one do you want to use, do you want to use AppLovin as a mediation or just AppLovin?

Are you on discord

**Comment by MiqueiasDevGames** [comment]
> 

The Review App Rating is not something that obeys all your calls, google prevents you from calling it too often, so it will only appear a few times or up to 1 a month.


I'm not on discord

try this plugin https://github.com/pschw/InAppReview

**Comment by ghost** [comment]
> > 
> 
> The Review App Rating is not something that obeys all your calls, google prevents you from calling it too often, so it will only appear a few times or up to 1 a month.
> 
> 
> I'm not on discord
> 
> try this plugin https://github.com/pschw/InAppReview

That's okay. But how can i set up it by code. I am getting this problem ![157589782-9213ee8e-7c6b-41c1-9ddb-88723a5e8885.png](https://user-images.githubusercontent.com/92350126/157776549-62df234e-432e-4b85-b501-3ef5017b0372.png)

**Comment by MiqueiasDevGames** [comment]
Don't skip the steps, dude, look at GdScript, the editor is already giving you the reason for the error there in red

The plugin developer already leave an example code, you don't need to change anything, just call the function in the place you want

**Comment by ghost** [comment]
> Don't skip the steps, dude, look at GdScript, the editor is already giving you the reason for the error there in red
> 
> The plugin developer already leave an example code, you don't need to change anything, just call the function in the place you want

Are you on Facebook or Twitter. Give me you social link. I want to connect with you

**Comment by ghost** [comment]
> > 
> 
> The Review App Rating is not something that obeys all your calls, google prevents you from calling it too often, so it will only appear a few times or up to 1 a month.
> 
> 
> I'm not on discord
> 
> try this plugin https://github.com/pschw/InAppReview

Have you test this plugin? This plugin don't have any .gd file to use as  autoload.

**Comment by MiqueiasDevGames** [comment]
It's in the readme :+1:
Well, give it a study and you'll be able to make your games.
[https://docs.godotengine.org/en/stable/](https://docs.godotengine.org/en/stable/)

Stay with God, hugs!!!

**Comment by MiqueiasDevGames** [comment]
@hani09876 


`extends Node2D

var review 

# Called when the node enters the scene tree for the first time.
func _ready():

	start_in_app_review()



func start_in_app_review():

	if Engine.has_singleton("GodotGooglePlayInAppReview"):
		var in_app_review = Engine.get_singleton("GodotGooglePlayInAppReview")
		in_app_review.connect("on_request_review_success", self, "_on_request_review_success")
		in_app_review.connect("on_request_review_failed", self, "_on_request_review_failed")
		in_app_review.connect("on_launch_review_flow_success", self, "_on_launch_review_flow_success")


	in_app_review.requestReviewInfo()
	in_app_review.launchReviewFlow()


func _on_request_review_success():
	pass
func _on_request_review_failed():
	pass
func _on_launch_review_flow_success():
	pass
`

**Comment by MiqueiasDevGames** [comment]
@hani09876 

`extends Node2D

var in_app_review

func _ready():

	start_in_app_review()



func start_in_app_review():

	if Engine.has_singleton("GodotGooglePlayInAppReview"):
	        in_app_review = Engine.get_singleton("GodotGooglePlayInAppReview")
		in_app_review.connect("on_request_review_success", self, "_on_request_review_success")
		in_app_review.connect("on_request_review_failed", self, "_on_request_review_failed")
		in_app_review.connect("on_launch_review_flow_success", self, "_on_launch_review_flow_success")


		in_app_review.requestReviewInfo()

#signal
func _on_request_review_success():
	in_app_review.launchReviewFlow()

#signal
func _on_request_review_failed():
	in_app_review.requestReviewInfo()

#signal
func _on_launch_review_flow_success():
	print("ReviewAPP Success!")
`

**Comment by ghost** [comment]
> @hani09876 
> 
> `extends Node2D
> 
> var in_app_review
> 
> func _ready():
> 
> 	start_in_app_review()
> 
> 
> 
> func start_in_app_review():
> 
> 	if Engine.has_singleton("GodotGooglePlayInAppReview"):
> 	        in_app_review = Engine.get_singleton("GodotGooglePlayInAppReview")
> 		in_app_review.connect("on_request_review_success", self, "_on_request_review_success")
> 		in_app_review.connect("on_request_review_failed", self, "_on_request_review_failed")
> 		in_app_review.connect("on_launch_review_flow_success", self, "_on_launch_review_flow_success")
> 
> 
> 		in_app_review.requestReviewInfo()
> 
> #signal
> func _on_request_review_success():
> 	in_app_review.launchReviewFlow()
> 
> #signal
> func _on_request_review_failed():
> 	in_app_review.requestReviewInfo()
> 
> #signal
> func _on_launch_review_flow_success():
> 	print("ReviewAPP Success!")
> `

Thank for your response. You are so helpful. I didn't find someone who helps me like you. You are really a good person. I appreciate you.

**Comment by MiqueiasDevGames** [comment]
@hani09876 

In this case, you helped me, I started using the plugin you mentioned, but in this case I made some changes to this script, because the way I left it there, it was giving me some errors, nothing to stop it from working, but it's always good to remove these error, see how it turned out: https://github.com/MiqueiasDevGames/export-godot-to-android-without-gradle-32bits-and-64bits/blob/master/Scripts_Godot/Review%20APP%20Rating/appreview.gd

**Comment by ghost** [comment]
> @hani09876 
> 
> In this case, you helped me, I started using the plugin you mentioned, but in this case I made some changes to this script, because the way I left it there, it was giving me some errors, nothing to stop it from working, but it's always good to remove these error, see how it turned out: https://github.com/MiqueiasDevGames/export-godot-to-android-without-gradle-32bits-and-64bits/blob/master/Scripts_Godot/Review%20APP%20Rating/appreview.gd

❤️❤️❤️

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/92350126/158951038-5fc75f9f-23e8-4fb3-8e62-6e48b4cfbccd.png)


hi . would you please check this Screenshot . does everything is okay? [@abuhani73365291](https://twitter.com/abuhani73365291)
this is my twitter id. lets don't garbage you nice project.
